import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSeans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "A Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSeans.className}>{children}</body>
    </html>
  );
}
